# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180120_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
