# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180120_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='publication_date',
        ),
    ]
