# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180122_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateField(null=True, verbose_name='publication_date'),
        ),
    ]
