# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180122_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='publication_date'),
        ),
    ]
