# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-01 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180123_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text_preview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='text_preview_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_preview_no',
            field=models.TextField(null=True),
        ),
    ]
