# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-07 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180201_1657'),
        ('news', '0007_auto_20180206_1436'),
    ]

    operations = [
    ]
