# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-20 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20180120_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmapblock',
            name='houtspot_headline_four',
            field=models.CharField(blank=True, max_length=255, verbose_name='houtspot_headline_four'),
        ),
        migrations.AddField(
            model_name='indexmapblock',
            name='houtspot_headline_one',
            field=models.CharField(blank=True, max_length=255, verbose_name='houtspot_headline_one'),
        ),
        migrations.AddField(
            model_name='indexmapblock',
            name='houtspot_headline_three',
            field=models.CharField(blank=True, max_length=255, verbose_name='houtspot_headline_three'),
        ),
        migrations.AddField(
            model_name='indexmapblock',
            name='houtspot_headline_two',
            field=models.CharField(blank=True, max_length=255, verbose_name='houtspot_headline_two'),
        ),
    ]
