# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-20 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20180120_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[(b'no', 'Norwegian'), (b'en', 'English')], default=b'no', max_length=10, verbose_name='language'),
        ),
    ]
