# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20180122_2131'),
        ('page', '0014_auto_20180120_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='parthnersblock',
            name='logo',
            field=models.ManyToManyField(to='info.ParthnerLogo', verbose_name='Logo'),
        ),
    ]
