# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20180122_2142'),
        ('page', '0015_parthnersblock_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencesblock',
            name='logo',
            field=models.ManyToManyField(to='info.ParthnerLogo', verbose_name='Logo'),
        ),
    ]
