# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_referencesblock_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptindexblock',
            name='first_sheme_list',
            field=redactor.fields.RedactorField(blank=True, verbose_name='first_sheme_list'),
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='first_sheme_title',
            field=models.CharField(default='', max_length=255, verbose_name='first_sheme_title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='scheme_image',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='second_sheme_list',
            field=redactor.fields.RedactorField(blank=True, verbose_name='second_sheme_list'),
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='second_sheme_title',
            field=models.CharField(default='', max_length=255, verbose_name='second_sheme_title'),
            preserve_default=False,
        ),
    ]
