# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_auto_20180122_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmapblock',
            name='hotspot_five_text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='hotspot_five_text'),
        ),
        migrations.AddField(
            model_name='indexmapblock',
            name='hotspot_four_text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='hotspot_four_text'),
        ),
        migrations.AddField(
            model_name='indexmapblock',
            name='hotspot_one_text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='hotspot_one_text'),
        ),
        migrations.AddField(
            model_name='indexmapblock',
            name='hotspot_three_text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='hotspot_three_text'),
        ),
        migrations.AddField(
            model_name='indexmapblock',
            name='hotspot_two_text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='hotspot_two_text'),
        ),
        migrations.AddField(
            model_name='indexmapblock',
            name='houtspot_headline_five',
            field=models.CharField(blank=True, max_length=255, verbose_name='houtspot_headline_five'),
        ),
    ]
