# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_auto_20180122_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptindexblock',
            name='sub_title_four',
            field=models.CharField(blank=True, max_length=255, verbose_name='sub_title_four'),
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='sub_title_one',
            field=models.CharField(blank=True, max_length=255, verbose_name='sub_title_one'),
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='sub_title_three',
            field=models.CharField(blank=True, max_length=255, verbose_name='sub_title_three'),
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='sub_title_two',
            field=models.CharField(blank=True, max_length=255, verbose_name='sub_title_two'),
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='title_four',
            field=models.CharField(blank=True, max_length=255, verbose_name='title_four'),
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='title_one',
            field=models.CharField(blank=True, max_length=255, verbose_name='title_one'),
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='title_three',
            field=models.CharField(blank=True, max_length=255, verbose_name='title_three'),
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='title_two',
            field=models.CharField(blank=True, max_length=255, verbose_name='title_two'),
        ),
    ]
