# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-23 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_auto_20180123_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptindexblock',
            name='scheme_image',
        ),
        migrations.AddField(
            model_name='conceptindexblock',
            name='scheme_svg',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
