# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-25 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0024_auto_20180124_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesindexblock',
            name='additional_image',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesindexblock',
            name='consulting_image',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesindexblock',
            name='monitoring_image',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesindexblock',
            name='project_image',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
