# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_auto_20180125_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesindexblock',
            name='additional_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='servicesindexblock',
            name='consulting_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='servicesindexblock',
            name='monitoring_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='servicesindexblock',
            name='project_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
