# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_customersblock_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersblock',
            name='background_image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
