# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-06 14:36
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_auto_20180125_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencesblock',
            name='logo',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='info.ParthnerLogo', verbose_name='Logo'),
        ),
    ]
