# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-07 17:00
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0030_auto_20180206_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parthnersblock',
            name='logo',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='info.ParthnerLogo'),
        ),
    ]
