# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-07 17:05
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_auto_20180205_1856'),
        ('page', '0034_remove_parthnersblock_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parthnersblock',
            name='logo',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='info.ParthnerLogo'),
        ),
    ]
