# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-20 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_footer', models.CharField(max_length=255, verbose_name='adress')),
                ('adress_footer_en', models.CharField(max_length=255, null=True, verbose_name='adress')),
                ('adress_footer_no', models.CharField(max_length=255, null=True, verbose_name='adress')),
                ('email_footer', models.CharField(max_length=255, verbose_name='email')),
                ('phone_footer', models.CharField(max_length=255, verbose_name='phone_footer')),
            ],
            options={
                'ordering': ['adress_footer'],
                'verbose_name': 'Info',
                'verbose_name_plural': 'Info',
            },
        ),
    ]
