# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-20 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20180120_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='index_top_subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='index_top_subtitle'),
        ),
        migrations.AddField(
            model_name='info',
            name='index_top_subtitle_no',
            field=models.CharField(max_length=255, null=True, verbose_name='index_top_subtitle'),
        ),
        migrations.AddField(
            model_name='info',
            name='index_top_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='index_top_title'),
        ),
        migrations.AddField(
            model_name='info',
            name='index_top_title_no',
            field=models.CharField(max_length=255, null=True, verbose_name='index_top_title'),
        ),
    ]
