# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-20 15:50
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20180120_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='hotspot_four_text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='hotspot_four_text'),
        ),
        migrations.AddField(
            model_name='info',
            name='hotspot_one_text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='hotspot_one_text'),
        ),
        migrations.AddField(
            model_name='info',
            name='hotspot_three_text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='hotspot_three_text'),
        ),
        migrations.AddField(
            model_name='info',
            name='hotspot_two_text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='hotspot_two_text'),
        ),
    ]
