# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20180120_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='position')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone_number')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('in_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='in_link')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
