# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_contact_in_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParthnerLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
            ],
            options={
                'verbose_name': 'ParthnerLogo',
                'verbose_name_plural': 'ParthnerLogo',
            },
        ),
    ]
