# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_parthnerlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parthnerlogo',
            name='image_2x',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='parthnerlogo',
            name='image_3x',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='parthnerlogo',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='parthnerlogo',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
