# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20180122_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parthnerlogo',
            name='image_2x',
        ),
        migrations.RemoveField(
            model_name='parthnerlogo',
            name='image_3x',
        ),
    ]
