# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-22 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20180122_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='hotspot_four_text',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hotspot_four_text_en',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hotspot_four_text_no',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hotspot_one_text',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hotspot_one_text_en',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hotspot_one_text_no',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hotspot_three_text',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hotspot_three_text_en',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hotspot_three_text_no',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hotspot_two_text',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hotspot_two_text_en',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hotspot_two_text_no',
        ),
    ]
