# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-23 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20180122_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='in_profile_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='in_profile_link'),
        ),
    ]
