# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-25 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20180123_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_block_title', models.CharField(blank=True, max_length=200)),
                ('news_block_title_no', models.CharField(blank=True, max_length=200, null=True)),
                ('news_block_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('news_block_active', models.BooleanField(default=False)),
                ('services_block_title', models.CharField(blank=True, max_length=200)),
                ('services_block_title_no', models.CharField(blank=True, max_length=200, null=True)),
                ('services_block_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('services_block_active', models.BooleanField(default=False)),
                ('concept_block_title', models.CharField(blank=True, max_length=200)),
                ('concept_block_title_no', models.CharField(blank=True, max_length=200, null=True)),
                ('concept_block_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('concept_block_active', models.BooleanField(default=False)),
                ('map_block_title', models.CharField(blank=True, max_length=200)),
                ('map_block_title_no', models.CharField(blank=True, max_length=200, null=True)),
                ('map_block_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('map_block_active', models.BooleanField(default=False)),
                ('parthners_block_title', models.CharField(blank=True, max_length=200)),
                ('parthners_block_title_no', models.CharField(blank=True, max_length=200, null=True)),
                ('parthners_block_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('parthners_block_active', models.BooleanField(default=False)),
                ('customers_block_title', models.CharField(blank=True, max_length=200)),
                ('customers_block_title_no', models.CharField(blank=True, max_length=200, null=True)),
                ('customers_block_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('customers_block_active', models.BooleanField(default=False)),
                ('references_block_title', models.CharField(blank=True, max_length=200)),
                ('references_block_title_no', models.CharField(blank=True, max_length=200, null=True)),
                ('references_block_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('references_block_active', models.BooleanField(default=False)),
                ('contacts_block_title', models.CharField(blank=True, max_length=200)),
                ('contacts_block_title_no', models.CharField(blank=True, max_length=200, null=True)),
                ('contacts_block_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('contacts_block_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'MenuLinks',
                'verbose_name_plural': 'MenuLinks',
            },
        ),
    ]
