# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-25 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20180125_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('order',), 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
