# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-25 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20180125_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='logo_footer',
            field=models.FileField(upload_to=b''),
        ),
    ]
