# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-25 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_auto_20180125_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='news_page_top_image',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='news_top_title',
            field=models.CharField(default='', max_length=255, verbose_name='news_top_title'),
            preserve_default=False,
        ),
    ]
