# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-25 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_auto_20180125_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='news_top_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='news_top_title'),
        ),
        migrations.AddField(
            model_name='info',
            name='news_top_title_no',
            field=models.CharField(max_length=255, null=True, verbose_name='news_top_title'),
        ),
    ]
