# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-30 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_auto_20180125_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='logo_header',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
