# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-05 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_info_logo_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulinks',
            name='concept_block_active',
        ),
        migrations.RemoveField(
            model_name='menulinks',
            name='contacts_block_active',
        ),
        migrations.RemoveField(
            model_name='menulinks',
            name='news_block_active',
        ),
        migrations.RemoveField(
            model_name='menulinks',
            name='references_block_active',
        ),
        migrations.RemoveField(
            model_name='menulinks',
            name='services_block_active',
        ),
    ]
